export enum ErrorCode {
  UNAUTHENTICATED     = 'UNAUTHENTICATED',
  VALIDATION_ERROR    = 'VALIDATION_ERROR',
  LOAN_NOT_FOUND      = 'LOAN_NOT_FOUND',
  LOAN_ALREADY_CLOSED = 'LOAN_ALREADY_CLOSED',
  DUPLICATE_PAYMENT   = 'DUPLICATE_PAYMENT',
  INTERNAL_ERROR      = 'INTERNAL_ERROR',
}
